### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by ajsnyde** [bharath5673/depthai-slam#4]
```python3 main.py 
Connected cameras:  [<CameraBoardSocket.RGB: 0>, <CameraBoardSocket.LEFT: 1>, <CameraBoardSocket.RIGHT: 2>]
Traceback (most recent call last):
  File "/home/dread/depthai-slam/main.py", line 62, in <module>
    img, tripoints, kpts, matches = process(frame)
  File "/home/dread/depthai-slam/slam.py", line 17, in process
    pts1, pts2, kpts, matches = extractor.extract_keypoints(img=img)
  File "/home/dread/depthai-slam/extractor.py", line 21, in extract_keypoints
    kpts = [cv2.KeyPoint(p[0][0],p[0][1], _size=30) for p in pts]
  File "/home/dread/depthai-slam/extractor.py", line 21, in <listcomp>
    kpts = [cv2.KeyPoint(p[0][0],p[0][1], _size=30) for p in pts]
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'KeyPoint'
> Overload resolution failed:
>  - KeyPoint() missing required argument 'size' (pos 3)
```

**Comment by jackslife2022** [comment]
Hi，I am happy be here.  I think you should del the "_" of "_size" of the slam.py line 21,because the openCV update and have something differnet.
